
# this YAML file defines the parameters for the controller
controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: bicycle_steering_controller/BicycleSteeringController
      
    # joint state bradcaster to tell the robot state publisher the state of the joints
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_broad:
  ros__parameters:
    extra_joints: ["back_central_wheel_joint", "front_central_steer_joint"]


diff_cont:
  ros__parameters:
    publish_rate: 30.0
    reference_timeout: 0.5
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false # if false the feedback is on the velocity
    use_stamped_vel: true
    rear_wheels_names: ['back_central_wheel_joint']
    front_wheels_names: ['front_central_steer_joint']
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: true 

    wheelbase: 0.335
    front_wheel_radius: 0.056
    rear_wheel_radius: 0.056
    # front_wheel_track: 0.25
    # rear_wheel_track: 0.25
    # max_steering_speed: 1.0
    # max_steering_angle: 0.9

    # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    # twist_covariance_diagonal: {0.0, 7.0, 14.0, 21.0, 28.0, 35.0}
    # pose_covariance_diagonal: {0.0, 7.0, 14.0, 21.0, 28.0, 35.0}  

