twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      # joystick:
      #   topic   : cmd_vel_joy
      #   timeout : 0.5
      #   priority: 90
      
      joystick_inverse:
        topic   : cmd_vel_joy_inverse
        timeout : 0.5
        priority: 100


      